name: 'Perform Lint and Run Tests'
on:
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Perform linting
        run: npm run lint:fix
      - name: Run Tests
        run: npm run test
